version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: spring-postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network

volumes:
  postgres_data:

networks:
  spring-network:
    driver: bridge